<div class="off-canvas-wrapper">
    <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
      <!-- Menu -->
      <div class="off-canvas position-left reveal-for-large adminmenu" id="offCanvas" data-off-canvas>
        <!-- Logo -->
        <img class="logo" src="/img/logo.png">

        <hr> <!-- User Section -->
        <div class="usercontent">
          <h6>Hey! <b>{username}</b></h6>
          <a href="/logout" class="button alert tiny expanded">Logout</a>
        </div>

        <hr>
        <!-- Menu -->
        <ul class="menu vertical">
          <li><a href="/admin"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a></li>
          <li><a href="/admin/phones"><i class="fa fa-fw fa-phone"></i> Phones</a></li>
          <li><a href="/admin/firmware"><i class="fa fa-fw fa-download"></i> Firmware</a></li>
        </ul>
      </div>
      <!-- End Menu -->