
      <!-- Page Content -->
      <div class="off-canvas-content maincontent" data-off-canvas-content>
        <div class="page-head with-bg">
          <button type="button" class="button secondary hide-for-large" data-toggle="offCanvas"><i class="fa fa-fw fa-bars"></i></button>
          <h3>Dashboard</h3>
          <p>Where it begins</p>
        </div>

        <div class="page-inner">
          <div class="row">

            <div class="medium-3 columns">
              <div class="callout"><h5>Deployed Phones</h5><h4>20</h4></div>
            </div>

            <div class="medium-3 columns">
              <div class="callout"><h5>Total Drivers</h5><h4>{drivercount}</h4></div>
            </div>

            <div class="medium-3 columns">
              <div class="callout"><h5>...</h5><h4>54</h4></div>
            </div>

            <div class="medium-3 columns">
              <div class="callout"><h5>...</h5><h4>7</h4></div>
            </div>

        </div>

        <div class="row">
          <div class="medium-7 columns">
            <div class="callout">
              <p>Welcome to CiscoSIPConfigServer v1.0 name is WIP if you cant tell</p>
              <p>A all in one solution for generating and serving config files for Cisco Unified phones, no more brain numbing XML files.</p>
              <p>To get started add a new phone in the sidebar.</p>
            </div>
          </div>

          <div class="medium-5 columns">
            <div class="callout">
              <a href="/logout" class="button alert tiny expanded">Logout</a>
            </div>
          </div>
        </div>


      </div>
      <!-- End Page Content -->
    </div>
  </div>
  </div>