


      <!-- Page Content -->
      <div class="off-canvas-content maincontent" data-off-canvas-content>
        <div class="page-head with-bg">
          <button type="button" class="button secondary hide-for-large" data-toggle="offCanvas"><i class="fa fa-fw fa-bars"></i></button>
          <h3>Firmware</h3>
          <p>The first stage to getting your Cisco phone working with SIP</p>
        </div>

        <div class="page-inner">

        <div class="row">
          <a class="button success" href="/admin/firmware/new">Upload</a>
        </div>
        <div class="row">
        <ul>
        {firmwarelist}
        </ul>
        </div>


      </div>
      <!-- End Page Content -->
    </div>
  </div>
  </div>