  <div class="row logincontainer">
      <div class="medium-5 large-6 columns ">
        <img src="img/logo.png"><hr>
        <p class="light">Login with your username and password</p>
        <small>Powered by CiscoSiPConfigServer v{ver}</small>
      </div>
      <div class="medium-7 large-6 columns leftborder loginbox">



            <label>Username
              <input type="text" placeholder="Username" tabindex=1 autofocus>
            </label>
 
      <label>Password
        <input type="password" placeholder="Password" tabindex=3>
      </label>
      <button href="#" type="submit" class="button large black expanded" tabindex=4>Login</button>

    </div>